### ISSUE TITLE
Collapse branches into single branch

### ISSUE THREAD

**Issue by danehrlich1** [CRS-support/modsecurity-docker#24]
There should be a single branch for all these Docker images. Usually this is the pattern most orgs do. See what Nginx does: https://github.com/nginxinc/docker-nginx

Because we don't have this right now, this repo looks very unmaintained, even though in reality it's not, it's just the latest commits are on a different branch than the one users land one when they first click.

Let me think of a folder structure and then submit to you all for approval / a first glance

@franbuehler @csanders-git

**Comment by bittner** [comment]
Any progress on this?

**Comment by bittner** [comment]
Update on the progress:

* We now have a `master` branch with a flattened directory structure of the images that are meant be be based on the official Web proxy base images (nginx, httpd).

Left to do:

* Configure automatic Docker builds on Docker Hub.
* Configure `master` as the main branch.
* Decide on what to do with the other branches.

For details see #32. Any input there is welcome!

I believe we can close this issue.
