### ISSUE TITLE
Unclear ENV variables

### ISSUE THREAD

**Issue by thisis2394** [CRS-support/modsecurity-docker#49]
Hi All,

not sure if this the right place to ask, apologies in advance

I am having trouble understanding  where the below big list of  env variable are being used inside container, I am aware what is the pupose of each of these env's but what i don't understand is that where is this being used in inside the image/container. Can someone help me out on this. 

Branch: master

![image](https://user-images.githubusercontent.com/60549807/84390085-b25d3e00-ac14-11ea-8ebc-c8fe2c1c0e20.png)

**Comment by codeguy** [comment]
These are added as environment variables inside the running container (run `env` in the container bash shell to see them). The entrypoint.sh file uses `envsbust` to find/replace these values in the neecssary config files before Nginx starts.

**Comment by thisis2394** [comment]
@codeguy  thanks for the reply.  Totally make sense now.

Any way is see this docker-entrypoint.sh is enabled only for nginx Dockerfiles and Apache the same doesn't apply 

https://github.com/CRS-support/modsecurity-docker/blob/master/v2-apache/Dockerfile

**Comment by bittner** [comment]
Apache interprets environment variables directly. Hence, we don't need to do `envsubst` magic in the entrypoint. This is only needed for Nginx (and I wish it were not). :smirk:
